import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import boundaries from "eslint-plugin-boundaries";

// Als Const herausgezogen, weil Flat-Config Rule-Einträge ÜBERSCHREIBT statt
// mergt: der server-only-Leak-Guard weiter unten konfiguriert
// no-restricted-syntax für app/** erneut und muss den Em-Dash-Eintrag
// mitführen, sonst wäre das Em-Dash-Gate für app/** still deaktiviert.
const EM_DASH_RESTRICTION = {
  // Ein :matches()-Selector statt drei nahezu identischer Einträge.
  // Die AST-Knoten-Info (Literal/JSXText/TemplateElement) ist für den
  // Entwickler aus Zeile + Kontext sichtbar; eine gemeinsame Message
  // reicht und reduziert Duplikation.
  selector:
    ":matches(Literal[value=/\\u2014/], JSXText[value=/\\u2014/], TemplateElement[value.raw=/\\u2014/])",
  message:
    "Em-Dash (—, U+2014) in UI-Text. Satz umformulieren, nicht mechanisch durch Komma ersetzen. Beispiele: docs/writing-style.md.",
};

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Python-Venv vom SPECTER2-Embedding-Setup — enthält torch/sklearn JS-Dateien
    // die ESLint mitscannt; sind aber third-party und nicht unsere Verantwortung.
    "scripts/embeddings/.venv/**",
    // fumadocs-mdx codegen output (regenerated by `predev`/`prebuild` scripts).
    // The generated server.ts/browser.ts/dynamic.ts carry `// @ts-nocheck`
    // and use webpack-loader query syntax that ESLint can't parse.
    ".source/**",
    // Generated coverage report (vitest --coverage); not source.
    "coverage/**",
    // Claude-Design-Referenzen (Phase 0 Redaktionsboard) — Mock-Runtime und
    // Templates, kein App-Code; werden nur als Spez gelesen.
    "docs/design/**",
  ]),
  {
    rules: {
      // Off — low signal in a German text corpus where straight quotes inside
      // EXPL bodies and prose are common (15+ violations in lib/explanations.tsx
      // alone). If we want consistent typography, the right move is German
      // curly quotes („…") in a separate pass — not entity-escaping.
      "react/no-unescaped-entities": "off",

      // Warn (not error) — react-hooks 7.x flags every `setState` inside
      // useEffect, including legitimate localStorage-sync and fetch-loading
      // patterns. The proper fix is useSyncExternalStore for localStorage and
      // Suspense / a data-fetching lib for the fetches; that's a larger
      // refactor (see use-leaderboard.ts, beeswarm-view.tsx, settings/page.tsx).
      // Surfaced as warning so the signal stays visible without blocking CI.
      "react-hooks/set-state-in-effect": "warn",

      // Allow `_`-prefixed args/vars as intentional-unused convention.
      // Used for Next.js route handlers and helpers that take but don't read
      // a parameter (e.g. `getSupabaseFromRequest(_req)`). Universal JS/TS
      // pattern that lint should respect.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
    },
  },
  // Em-Dash-Gate für user-sichtbare UI-Strings. Standard: docs/writing-style.md.
  // Triggert auf U+2014 (—) in String-Literals, JSX-Text und Template-Literals.
  // Scope: UI-Code (app/, components/, lib/client/**, lib/shared/**).
  // NICHT lib/server/** (Log-Strings und Error-Messages dürfen em-dashes
  // haben) und NICHT scripts/** (Operations).
  // Comments (JSDoc, //) sind im AST kein Literal/JSXText/TemplateElement und
  // werden vom Selector korrekt nicht erfasst.
  // MDX-Content (content/help/**) wird separat über `npm run check-em-dashes`
  // geprüft (grep-basiert; MDX braucht eslint-plugin-mdx, das wir nicht haben).
  // Beide Gates laufen in CI als eigene Steps (siehe .github/workflows/ci.yml).
  {
    files: [
      "app/**/*.{ts,tsx}",
      "components/**/*.{ts,tsx}",
      "lib/client/**/*.{ts,tsx}",
      "lib/shared/**/*.{ts,tsx}",
    ],
    // Test-Files raus: Vitest/Jest-Test-Beschreibungen sind konventionell
    // englisch, und englische Texte dürfen em-dashes haben.
    ignores: ["**/*.test.{ts,tsx}", "**/*.spec.{ts,tsx}"],
    rules: {
      "no-restricted-syntax": ["error", EM_DASH_RESTRICTION],
    },
  },
  // Phase-2 architecture-boundaries hardening (Plan §6.3 + §6.6 step 5).
  // - Uses boundaries/dependencies (v6 rule name; element-types is the
  //   deprecated v5 name).
  // - default: "disallow" means every cross-element import must be on an
  //   explicit allow list; everything outside (third-party packages,
  //   unclassified files) is silently allowed by the plugin's
  //   checkAllOrigins/checkUnknownLocals defaults.
  // - level: "error" — CI fails on new violations.
  //
  // Selector form: object-based entity selectors (v7). Migrated from the
  // string/tuple legacy form 2026-07-06 alongside the v6→v7 bump; the
  // deprecation notice ("Consider migrating to object-based selectors" +
  // "'rules' option is deprecated") is now silent. v7 renamed the option
  // `rules` → `policies` and each policy uses `from: { element: { type } }` /
  // `allow: { to: { element: { types: [...] } } }`.
  //
  // Pattern order matters (first-match-wins): app/api/** must come BEFORE
  // app/** so route handlers resolve to api-routes, not app-pages.
  {
    plugins: { boundaries },
    settings: {
      "boundaries/elements": [
        { type: "server", pattern: "lib/server/**" },
        { type: "shared", pattern: "lib/shared/**" },
        { type: "client", pattern: "lib/client/**" },
        { type: "api-routes", pattern: "app/api/**" },
        { type: "app-pages", pattern: "app/**" },
        { type: "components", pattern: "components/**" },
        { type: "scripts", pattern: "scripts/**" },
      ],
    },
    rules: {
      "boundaries/dependencies": [
        "error",
        {
          default: "disallow",
          policies: [
            // shared is the kernel — no project-internal deps
            {
              from: { element: { type: "shared" } },
              allow: { to: { element: { types: ["shared"] } } },
            },
            // server can call into shared + other server modules
            {
              from: { element: { type: "server" } },
              allow: { to: { element: { types: ["shared", "server"] } } },
            },
            // client must NOT reach into server (would leak into the bundle)
            {
              from: { element: { type: "client" } },
              allow: { to: { element: { types: ["shared", "client"] } } },
            },
            // components are pure UI; no server, no app-pages, no api-routes
            {
              from: { element: { type: "components" } },
              allow: {
                to: { element: { types: ["shared", "client", "components"] } },
              },
            },
            // app-pages compose client/components AND — since the Phase-A4
            // RSC pilot (ADR 0009) — directly call thin server entry points
            // for first-paint data. Bundle leaks into client code are still
            // caught at build time by Next.js's `'use client'` boundary +
            // Webpack server-only resolution for `postgres`, `crypto`, etc.;
            // a 'use client' page MUST NOT import @/lib/server/* — machinell
            // erzwungen durch den no-restricted-syntax-Guard weiter unten
            // (boundaries kann Dateien nur nach Pfad, nicht nach Directive
            // klassifizieren, deshalb steht die Regel separat).
            {
              from: { element: { type: "app-pages" } },
              allow: {
                to: {
                  element: {
                    types: [
                      "shared",
                      "client",
                      "components",
                      "app-pages",
                      "server",
                    ],
                  },
                },
              },
            },
            // api-routes are the only surface that bridges to server
            {
              from: { element: { type: "api-routes" } },
              allow: {
                to: { element: { types: ["server", "shared", "api-routes"] } },
              },
            },
            // scripts run offline / in cron; need server enrichment clients
            {
              from: { element: { type: "scripts" } },
              allow: {
                to: { element: { types: ["shared", "server", "scripts"] } },
              },
            },
          ],
        },
      ],
    },
  },
  // server-only-Leak-Guard (Architektur-Audit #9): boundaries erlaubt
  // app→lib/server für RSC-First-Paint-Daten (ADR 0009), kann aber nicht
  // zwischen Server- und Client-Komponenten unterscheiden (Elemente sind
  // rein pfadbasiert; die 'use client'-Directive steht IM Dateiinhalt).
  // Dieser Guard schließt die Lücke ohne Custom-Rule: esquery erkennt die
  // Directive über das ESTree-Feld `directive` auf dem top-level
  // ExpressionStatement und verbietet dann jeden statischen Import von
  // lib/server (Alias `@/…` und relative Pfade).
  // esquery-Eigenheiten (beide getestet, s. Bericht 2026-08-31):
  //   - `:has(> …)` (führender Child-Kombinator) wird nicht unterstützt und
  //     matcht still gar nichts — deshalb `:has(Program > …)`, was dieselbe
  //     "direktes Kind von Program"-Bedingung ausdrückt (und Directives in
  //     verschachtelten Funktionskörpern korrekt NICHT matcht).
  //   - `/` in Regex-Literalen als `/` schreiben; escapte Slashes
  //     parst der Selector-Parser nicht.
  // Scope: app/** — components/** und lib/client/** sind via boundaries
  // ohnehin komplett von lib/server abgeschnitten (directive-unabhängig).
  // Dieser Block ÜBERSCHREIBT no-restricted-syntax des Em-Dash-Blocks für
  // app/** (Flat-Config mergt Rule-Optionen nicht) und führt dessen Eintrag
  // deshalb mit — inklusive gleicher Test-Ignores, damit Test-Dateien wie
  // bisher em-dash-frei bleiben dürfen.
  {
    files: ["app/**/*.{ts,tsx}"],
    ignores: ["**/*.test.{ts,tsx}", "**/*.spec.{ts,tsx}"],
    rules: {
      "no-restricted-syntax": [
        "error",
        EM_DASH_RESTRICTION,
        {
          // [importKind="value"]: `import type { … }` ist erlaubt — wird vom
          // Compiler wegradiert und landet nie im Bundle. Client-Komponenten
          // typisieren ihre Props legitim mit den Rückgabetypen der
          // Server-Fetcher (z.B. DashboardData aus lib/server/dashboard).
          selector:
            'Program:has(Program > ExpressionStatement[directive="use client"]) > ImportDeclaration[importKind="value"][source.value=/^(?:@\\u002F|(?:\\.\\.?\\u002F)+)lib\\u002Fserver(?:\\u002F|$)/]',
          message:
            "'use client'-Datei importiert lib/server — das zieht Server-Code (DB-Client, Secrets) in das Client-Bundle. Daten per RSC-Parent laden und als Props reichen, oder eine API-Route aufrufen.",
        },
      ],
    },
  },
]);

export default eslintConfig;
