import 'server-only';
import { docs } from '@/.source/server';
import { loader } from 'fumadocs-core/source';

// `.source/server.ts` is generated by `fumadocs-mdx` from content/help/*.mdx
// and content/help/**/meta.json. Re-generated by `predev` / `prebuild` /
// `typecheck`-script hooks; do not import in a Client Component (server-only).
export const source = loader({
  baseUrl: '/help',
  source: docs.toFumadocsSource(),
});
