/** WebDB master-data wire DTOs: persons, orgunits, projects, lectures and the
 *  ÖSTAT taxonomy — the author/affiliation model behind publications. */

export interface Person {
  id: string;
  webdb_uid: number;
  firstname: string;
  lastname: string;
  degree_before: string | null;
  degree_after: string | null;
  email: string | null;
  orcid: string | null;
  oestat3_name_de: string | null;
  oestat3_name_en: string | null;
  research_fields: string | null;
  external: boolean;
  deceased: boolean;
  portrait: string | null;
  slug: string | null;
}

export interface Orgunit {
  id: string;
  webdb_uid: number;
  name_de: string;
  name_en: string | null;
  akronym_de: string | null;
  akronym_en: string | null;
  url_de: string | null;
  url_en: string | null;
  parent_id: string | null;
  /** Depth from the closest root (parent_id NULL). Computed by the
   *  /api/orgunits handler; absent on detail-page joins. */
  tier?: number;
  /** Tier-4 leaf with a non-structural name and a German acronym —
   *  i.e. an actual research-producing institute. Computed alongside
   *  `tier`. */
  is_research_unit?: boolean;
}

export interface Project {
  id: string;
  webdb_uid: number;
  title_de: string | null;
  title_en: string | null;
  summary_de: string | null;
  summary_en: string | null;
  thematic_focus_de: string | null;
  thematic_focus_en: string | null;
  funding_type_de: string | null;
  funding_type_en: string | null;
  starts_on: string | null;
  ends_on: string | null;
  cancelled: boolean;
  url_de: string | null;
  url_en: string | null;
}

export interface Lecture {
  id: string;
  webdb_uid: number;
  original_title: string;
  lecture_date: string | null;
  city: string | null;
  event_name: string | null;
  event_type: string | null;
  popular_science: boolean;
  speaker: string | null;
  citation: string | null;
}

/** Wire shape returned by `/api/oestat6` — the row plus the server-computed
 *  `super_domain` (1-digit prefix of webdb_uid, the top-level Frascati branch).
 *  `oestat3` is the 3-digit subdomain code and is generated by the DB from
 *  webdb_uid; the column is nullable in the introspected schema (Drizzle
 *  types generated columns conservatively) even though it is non-null in
 *  practice when webdb_uid is set. */
export interface Oestat6 {
  id: string;
  webdb_uid: number;
  oestat3: number | null;
  name_de: string;
  name_en: string;
  super_domain: number;
  super_domain_label: string | null;
}

export interface PersonPublication {
  person_id: string;
  publication_id: string;
  highlight: boolean;
  mahighlight: boolean;
  authorship: string | null;
}

export interface OrgunitPublication {
  orgunit_id: string;
  publication_id: string;
  highlight: boolean;
}
