/**
 * Zentrales Icon-Modul (Design-Rollout Phase C, DESIGN_SYSTEM.md §7 + §8.4).
 *
 * Die App wurde ursprünglich auf lucide-react gebaut; das Design Book verlangt
 * Phosphor Icons. Statt 108 Dateien + ~340 Call-Sites einzeln umzuschreiben,
 * bildet dieses Modul jeden benutzten lucide-Namen auf sein Phosphor-Äquivalent
 * ab und re-exportiert es unter dem vertrauten Namen. Call-Sites tauschen nur
 * den Import-Pfad ("lucide-react" -> "@/lib/icons"); JSX/Props (className/size)
 * bleiben unverändert (Tailwind h-/w-/size-* überschreiben Phosphors 1em-Default).
 *
 * Namensgebung: linker Name = Phosphor-Quelle, rechter Name = beibehaltener
 * lucide-Bezeichner. Mapping-Rationale in DESIGN_SYSTEM §7 (Bedeutungstabelle).
 * Für neue Icons direkt Phosphor-Namen aus "@phosphor-icons/react/dist/ssr" nehmen.
 *
 * WICHTIG: Value-Re-Exports gehen über den SSR/RSC-sicheren Entry
 * "@phosphor-icons/react/dist/ssr" — der Haupt-Entry legt beim Modul-Load einen
 * React-Context (IconContext, createContext) an, was in Server-Components
 * (z. B. /_not-found) den Build bricht. Die SSR-Icons sind context-frei und
 * akzeptieren className/size/weight weiterhin direkt (wir nutzen keinen Provider).
 */
import type { Icon } from "@phosphor-icons/react";

/** Kompat-Alias: früher lucide-react's LucideIcon-Typ, jetzt Phosphors Icon. */
export type LucideIcon = Icon;

export {
  ClockCountdown as AlarmClock,
  WarningCircle as AlertCircle,
  Warning as AlertTriangle,
  Archive as Archive,
  ArrowDown as ArrowDown,
  ArrowDownRight as ArrowDownRight,
  ArrowLeft as ArrowLeft,
  ArrowRight as ArrowRight,
  ArrowLineRight as ArrowRightToLine,
  ArrowUp as ArrowUp,
  ArrowsDownUp as ArrowUpDown,
  ArrowUpRight as ArrowUpRight,
  Trophy as Award,
  ChartBar as BarChart3,
  BookOpen as BookOpen,
  BookOpenText as BookText,
  Brain as Brain,
  Building as Building,
  Buildings as Building2,
  Calendar as Calendar,
  CalendarDots as CalendarDays,
  Calendar as CalendarIcon,
  CalendarBlank as CalendarRange,
  Camera as Camera,
  Check as Check,
  CheckCircle as CheckCircle2,
  Check as CheckIcon,
  CaretDown as ChevronDown,
  CaretDown as ChevronDownIcon,
  CaretLeft as ChevronLeft,
  CaretLeft as ChevronLeftIcon,
  CaretRight as ChevronRight,
  CaretRight as ChevronRightIcon,
  CaretUp as ChevronUp,
  CaretUp as ChevronUpIcon,
  CaretUpDown as ChevronsUpDown,
  CheckCircle as CircleCheckIcon,
  Question as CircleHelp,
  Circle as CircleIcon,
  ClipboardText as ClipboardCheck,
  Clock as Clock,
  Columns as Columns3,
  Copy as Copy,
  ArrowElbowDownLeft as CornerDownLeft,
  Crown as Crown,
  Database as Database,
  Download as Download,
  ArrowSquareOut as ExternalLink,
  Eye as Eye,
  EyeSlash as EyeOff,
  File as File,
  FileZip as FileArchive,
  FileDashed as FileQuestion,
  FileText as FileText,
  FolderOpen as FolderOpen,
  Globe as Globe,
  DotsSixVertical as GripVertical,
  Hash as Hash,
  Heart as Heart,
  Question as HelpCircle,
  ClockCounterClockwise as History,
  Image as Image,
  Info as Info,
  Info as InfoIcon,
  Kanban as Kanban,
  Key as Key,
  Keyboard as Keyboard,
  Stack as Layers,
  Link as Link,
  LinkSimple as Link2,
  List as List,
  ListChecks as ListChecks,
  ListBullets as ListTree,
  CircleNotch as Loader2,
  CircleNotch as Loader2Icon,
  Lock as Lock,
  LockKey as LockKeyhole,
  SignIn as LogIn,
  SignOut as LogOut,
  Envelope as Mail,
  MapPin as MapPin,
  ArrowsOut as Maximize2,
  Medal as Medal,
  Megaphone as Megaphone,
  List as Menu,
  ChatCircle as MessageCircle,
  ChatCircleDots as MessageSquarePlus,
  Microphone as Mic,
  Minus as Minus,
  Monitor as Monitor,
  Moon as Moon,
  DotsThree as MoreHorizontal,
  Newspaper as Newspaper,
  XCircle as OctagonXIcon,
  Paperclip as Paperclip,
  Pause as Pause,
  PenNib as PenTool,
  Pencil as Pencil,
  PushPin as Pin,
  Play as Play,
  Plus as Plus,
  Crosshair as Radar,
  Broadcast as Radio,
  ArrowsClockwise as RefreshCcw,
  ArrowsClockwise as RefreshCw,
  ArrowCounterClockwise as RotateCcw,
  FloppyDisk as Save,
  MagnifyingGlass as Search,
  MagnifyingGlass as SearchIcon,
  MagnifyingGlassMinus as SearchX,
  PaperPlaneTilt as Send,
  Gear as Settings,
  Shield as Shield,
  ShieldCheck as ShieldCheck,
  SlidersHorizontal as SlidersHorizontal,
  Sparkle as Sparkles,
  Square as Square,
  ArrowSquareOut as SquareArrowOutUpRight,
  Star as Star,
  Sun as Sun,
  Tag as Tags,
  Terminal as Terminal,
  Trash as Trash2,
  TrendUp as TrendingUp,
  Warning as TriangleAlert,
  Warning as TriangleAlertIcon,
  ArrowUUpLeft as Undo2,
  Upload as Upload,
  User as User,
  UserCircle as UserCircle2,
  UserMinus as UserMinus,
  UserPlus as UserPlus,
  Users as Users,
  Wrench as Wrench,
  X as X,
  XCircle as XCircle,
  X as XIcon,
  MagnifyingGlassPlus as ZoomIn,
} from "@phosphor-icons/react/dist/ssr";
